[build]
command = "yarn build" # && yarn build-storybook && yarn verify-sitemap ${URL} ${DEPLOY_URL}
publish = "public"

[build.environment]
YARN_FLAGS = "--no-ignore-optional"
YARN_VERSION = "1.9.4"

[dev]
command = "yarn start"
framework = "gatsby"

[[redirects]]
force = true
from = "/bigtest/docs/interactors/*"
status = 301
to = "https://frontside.com/interactors"

[[redirects]]
force = true
from = "/bigtest/*"
status = 200
to = "https://bigtest.netlify.app/bigtest/:splat"

[[redirects]]
force = true
from = "/platformscript/*"
status = 200
to = "https://platformscript.deno.dev/:splat"
headers = {X-Base = "https://frontside.com/platformscript/", X-Fresh-Base-Url = "https://frontside.com/platformscript/" }

[[redirects]]
force = true
from = "/workshops/*"
status = 200
to = "https://frontside.deno.dev/workshops/:splat"

[[redirects]]
force = true
from = "/interactors/html/api"
status = 301
to = "/interactors/html/api/index.html"

[[redirects]]
force = true
from = "/interactors/html/api/*"
status = 200
to = "https://main--interactors-html-api.netlify.app/:splat"

[[redirects]]
force = true
from = "/interactors/mui/api"
status = 301
to = "/interactors/mui/api/index.html"

[[redirects]]
force = true
from = "/interactors/mui/api/*"
status = 200
to = "https://main--interactors-mui-api.netlify.app/:splat"

[[redirects]]
force = true
from = "/interactors/*"
status = 200
to = "https://interactors.netlify.app/interactors/:splat"

[[redirects]]
force = true
from = "https://frontside.io/*"
status = 301
to = "https://frontside.com/:splat"

[[redirects]]
force = true
from = "https://www.frontside.io/*"
status = 301
to = "https://frontside.com/:splat"

[[headers]]
for = "/bigtest/asciinema/iframes/cross-platform.html"
[headers.values]
X-Frame-Options = "SAMEORIGIN"

[[headers]]
for = "/storybook*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"

[functions]
  directory = "src/lambda-functions"
