name: test

on: pull_request

jobs:
  stable-urls:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - run: |
           yarn
           yarn check-urls
        working-directory: ./legacy
        id: url-hash

      - run: |
          yarn build
          git diff sitemap.txt
          yarn check-urls ${{ steps.url-hash.outputs.url-hash }}
        working-directory: ./legacy
        env:
          SIMPLECAST_API: ${{ secrets.SIMPLECAST_API }}
